#define TAPPING_TERM 100
#undef RGBLIGHT_ENABLE
#undef RGB_MATRIX_ENABLE
#undef MOUSEKEY_ENABLE
#define NO_ACTION_ONESHOT

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define RETRO_TAPPING_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
